name: PolymerHelloWorld
environment:
  sdk: any

dependencies:
  browser: any
  polymer: any
  shadow_dom: any
  mdv: any
  event_bus: any

transformers:
-  polymer:
    entry_points:
    - web/index.html
    - web/hello-world/event-consumer.html
    - web/stopwatch/stopwatch.html