name: polymer_hello_world

environment:
  sdk: any

dependencies:
  polymer_elements:
    git: https://github.com/ErikGrimes/polymer_elements

  polymer_ui_elements:
    git: https://github.com/ErikGrimes/polymer_ui_elements

  angular:
    git: https://github.com/MikeMitterer/angular.dart
    # git: https://github.com/angular/angular.dart

  json: any
  validate: any

transformers:
- angular

-  polymer:
    entry_points:
    - web/index.html

    - example/mm_hello_world/index.html
    - example/mm_test_data/index.html